name: 'Bump Version & Create Tag'

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump-version:
    if: "!contains(github.event.head_commit.message, 'chore: Bump version')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js & Bun & Configure Git
        # Мы используем локальный Action, чтобы не повторять код
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bump version, create commit and tag
        run: |
          # Эта команда сама увеличит версию, создаст коммит и тег
          npm version patch -m "chore: Bump version to %s"

      - name: Push changes and tags
        run: |
          # Мы даем прямой приказ с прямым токеном. У него нет выбора.
          git push --follow-tags https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
