name: 'Bump Version & Create Tag'
  on:
    push:
      branches:
        - master

  permissions:
    contents: write

  jobs:
    bump-version:
      if: "!contains(github.event.head_commit.message, 'chore: Bump version')"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup
        - run: bun install --frozen-lockfile
        - name: Bump version and create commit
          id: bump_version
          run: |
            npm version patch -m "chore: Bump version to %s"
            NEW_VERSION=$(node -p "require('./package.json').version")
            echo "tag_name=v$NEW_VERSION" >> $GITHUB_OUTPUT
        - name: Create Git Tag
          run: git tag ${{ steps.bump_version.outputs.tag_name }}
        - name: Push changes and tags
          run: git push --follow-tags https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
